apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: minimal-api
  annotations:
    github.com/project-slug: thomasnokleby/minimal-api
spec:
  type: other
  lifecycle: experimental
  owner: thomasnokleby@gmail.com
