apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: minimal-api
  annotations:
    github.com/project-slug: thomasnokleby/minimal-api
spec:
  type: openapi
  lifecycle: experimental
  owner: thomasnokleby@gmail.com
  definition: |
    openapi: 3.1.0
    info:
      title: FastAPI
      version: 0.1.0
    paths:
      "/":
        get:
          summary: Root
          operationId: root__get
          responses:
            '200':
              description: Successful Response
              content:
                application/json:
                  schema: {}
